@@ .. @@
  const vehicles: Vehicle[] = [
     {
       id: 'basic',
       name: 'Basic Car',
       price: 0,
       speed: 1,
       image: '🚗',
       unlocked: true,
     },
     {
       id: 'bmw',
-      name: 'BMW M3',
+      name: 'BMW M8 Competition',
       price: 25000,
       speed: 1.3,
       image: '🏎️',
       unlocked: gameState.unlockedCars.includes('bmw'),
     },
+    {
+      id: 'audi',
+      name: 'Audi R8 V10',
+      price: 45000,
+      speed: 1.6,
+      image: '🏎️',
+      unlocked: gameState.unlockedCars.includes('audi'),
+    },
     {
       id: 'lambo',
       name: 'Lamborghini Huracán',
-      price: 80000,
+      price: 120000,
       speed: 1.8,
       image: '🏎️',
       unlocked: gameState.unlockedCars.includes('lambo'),
     },
+    {
+      id: 'rolls',
+      name: 'Rolls Royce Phantom',
+      price: 200000,
+      speed: 1.5,
+      image: '🚐',
+      unlocked: gameState.unlockedCars.includes('rolls'),
+    },
     {
       id: 'bugatti',
       name: 'Bugatti Chiron',
-      price: 250000,
+      price: 350000,
       speed: 2.5,
       image: '🚗',
       unlocked: gameState.unlockedCars.includes('bugatti'),
     },
-    {
-      id: 'rolls',
-      name: 'Rolls Royce Phantom',
-      price: 180000,
-      speed: 1.5,
-      image: '🚐',
-      unlocked: gameState.unlockedCars.includes('rolls'),
-    },
   ];