@@ .. @@
  const vehicles: Vehicle[] = [
    {
      id: 'basic',
      name: 'Basic Car',
      price: 0,
      speed: 1,
-      image: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
      description: 'Your starter vehicle',
      unlocked: true,
    },
    {
      id: 'bmw',
-      name: 'BMW M3',
+      name: 'BMW M8 Competition',
       price: 25000,
       speed: 1.3,
-      image: 'https://images.pexels.com/photos/244206/pexels-photo-244206.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'German engineering at its finest',
       unlocked: gameData?.unlockedCars.includes('bmw') || false,
     },
+    {
+      id: 'audi',
+      name: 'Audi R8 V10',
+      price: 45000,
+      speed: 1.6,
+      image: 'https://images.pexels.com/photos/544542/pexels-photo-544542.jpeg?auto=compress&cs=tinysrgb&w=400',
+      description: 'Quattro all-wheel drive perfection',
+      unlocked: gameData?.unlockedCars.includes('audi') || false,
+    },
     {
       id: 'lambo',
       name: 'Lamborghini Huracán',
-      price: 80000,
+      price: 120000,
       speed: 1.8,
-      image: 'https://images.pexels.com/photos/544542/pexels-photo-544542.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/2127733/pexels-photo-2127733.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'Italian supercar excellence',
       unlocked: gameData?.unlockedCars.includes('lambo') || false,
     },
     {
-      id: 'bugatti',
-      name: 'Bugatti Chiron',
-      price: 250000,
-      speed: 2.5,
-      image: 'https://images.pexels.com/photos/1719648/pexels-photo-1719648.jpeg?auto=compress&cs=tinysrgb&w=400',
-      description: 'The ultimate hypercar',
-      unlocked: gameData?.unlockedCars.includes('bugatti') || false,
-    },
-    {
       id: 'rolls',
       name: 'Rolls Royce Phantom',
-      price: 180000,
+      price: 200000,
       speed: 1.5,
-      image: 'https://images.pexels.com/photos/1719648/pexels-photo-1719648.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/1592384/pexels-photo-1592384.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'Luxury redefined',
       unlocked: gameData?.unlockedCars.includes('rolls') || false,
     },
+    {
+      id: 'bugatti',
+      name: 'Bugatti Chiron',
+      price: 350000,
+      speed: 2.5,
+      image: 'https://images.pexels.com/photos/1719648/pexels-photo-1719648.jpeg?auto=compress&cs=tinysrgb&w=400',
+      description: 'The ultimate hypercar',
+      unlocked: gameData?.unlockedCars.includes('bugatti') || false,
+    },
   ];