@@ .. @@
  const cities: City[] = [
     {
       id: 'dubai',
       name: 'Dubai',
       cost: 0,
-      image: 'https://images.pexels.com/photos/162031/dubai-tower-arab-khalifa-162031.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/325193/pexels-photo-325193.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'City of Gold - Luxury and opportunity',
       unlocked: true,
     },
     {
       id: 'milano',
       name: 'Milano',
       cost: 15000,
-      image: 'https://images.pexels.com/photos/1797161/pexels-photo-1797161.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/1797161/pexels-photo-1797161.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'Fashion Capital - Style and business',
       unlocked: gameData?.cash >= 15000 || false,
     },
     {
       id: 'paris',
       name: 'Paris',
       cost: 20000,
-      image: 'https://images.pexels.com/photos/161853/eiffel-tower-paris-france-tower-161853.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/161853/eiffel-tower-paris-france-tower-161853.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'City of Light - Art and culture',
       unlocked: gameData?.cash >= 20000 || false,
     },
     {
       id: 'tokyo',
       name: 'Tokyo',
       cost: 35000,
-      image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'Tech Hub - Innovation and tradition',
       unlocked: gameData?.cash >= 35000 || false,
     },
     {
       id: 'newyork',
       name: 'New York',
       cost: 40000,
-      image: 'https://images.pexels.com/photos/290386/pexels-photo-290386.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/290386/pexels-photo-290386.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'Big Apple - Wall Street and dreams',
       unlocked: gameData?.cash >= 40000 || false,
     },
     {
       id: 'monaco',
       name: 'Monaco',
       cost: 60000,
-      image: 'https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&cs=tinysrgb&w=400',
+      image: 'https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&cs=tinysrgb&w=400',
       description: 'Monte Carlo - Ultimate luxury',
       unlocked: gameData?.cash >= 60000 || false,
     },
   ];